AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket for Frontend Deployment

Mappings:
  EnvMap:
    prod:
      BucketName: "metroplanner-frontend-prod"
      Domain: "ich-hab-plan.de"
      CertificateArn: "arn:aws:acm:us-east-1:891666753558:certificate/21b68b38-9184-4f8e-a51b-b0c4482e1e72"
      OriginId: prod-bucket
      Comment: PROD Metroplanner Distro
    dev:
      BucketName: "metroplanner-frontend-dev"
      Domain: "dev.ich-hab-plan.de"
      CertificateArn: "arn:aws:acm:us-east-1:891666753558:certificate/c1ebfcc3-a24c-4e9c-943e-cb66bb52ed97"
      OriginId: dev-bucket
      Comment: Metroplanner Distro DEV

Parameters:
  env:
    Type: String
    Description: Environment of the deployment (Lowercase)

# Conditions:
#   IsStaging: !Equals [!Ref env, prod]

Resources:
  MetroplannerCfDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !FindInMap [EnvMap, !Ref env, Domain]
        Comment: !FindInMap [EnvMap, !Ref env, Comment]
        # Staging: !If [IsStaging, false, true]
        PriceClass: PriceClass_100
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          Compress: true
          TargetOriginId: !FindInMap [EnvMap, !Ref env, OriginId]
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: "https-only"
            DomainName: !GetAtt MetroplannerBucket.DomainName
            Id: !FindInMap [EnvMap, !Ref env, OriginId]
        ViewerCertificate:
          AcmCertificateArn: !FindInMap [EnvMap, !Ref env, CertificateArn]
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
      Tags:
        - Key: App
          Value: metroplanner
        - Key: Environment
          Value: !Ref env
  MetroplannerBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !FindInMap [EnvMap, !Ref env, BucketName]
      Tags:
        - Key: App
          Value: metroplanner
        - Key: Environment
          Value: !Ref env
      WebsiteConfiguration:
        IndexDocument: index.html

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      PolicyDocument:
        Id: metroplannerPublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref MetroplannerBucket
                - /*
      Bucket: !Ref MetroplannerBucket

  # metroplannerDNSEntry:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     HostedZoneName: "ich-hab-plan.de."
  #     Comment: Zone apex alias.
  #     RecordSets:
  #       - Name: !FindInMap [EnvMap, !Ref env, Domain]
  #         Type: A
  #         AliasTarget:
  #           HostedZoneId: "Z21DNDUVLTQW6Q"
  #           DNSName: !Sub
  #             - "${BucketName}.s3-website-eu-central-1.amazonaws.com"
  #             - BucketName: !FindInMap [EnvMap, !Ref env, BucketName]
  #       # - Name: !Sub
  #       #     - www.${Do}
  #       #     - Do: !FindInMap [EnvMap, !Ref env, Domain]
  #       #   Type: CNAME
  #       #   TTL: 900
  #       #   ResourceRecords:
  #       #     - !GetAtt MetroplannerBucket.DomainName

Outputs:
  WebsiteURL:
    Value: !GetAtt MetroplannerBucket.WebsiteURL
    Description: URL for website hosted on S3
